### Find all users
GET http://localhost:8080/users
Accept: application/json
Content-Type: application/json

### Get user
GET http://localhost:8080/users/2
Content-Type: application/json
Accept: application/json

### Add user
POST http://localhost:8080/users
Content-Type: application/json
Accept: application/json

{
  "id" : 1,
  "login": "loginTestB",
  "password": "passwordTestB",
  "userRole": ["USER"]
}

### Update user
PUT http://localhost:8080/users
Content-Type: application/json
Accept: application/json

{
  "id": 4,
  "login": "loginUpdate",
  "password": "passwordUpdate",
  "userRole": ["ADMIN"]
}

### Delete user
DELETE http://localhost:8080/users/3
Content-Type: application/json
Accept: application/json
