### Find all users
GET http://localhost:8080/users
Accept: application/json
Content-Type: application/json

### Get user
GET http://localhost:8080/users/1
Content-Type: application/json
Accept: application/json

### Add user
POST http://localhost:8080/users
Content-Type: application/json
Accept: application/json

{
  "login": "loginTestB",
  "password": "passwordTestB",
  "userRoles": ["USER"]
}

### Update user
PUT http://localhost:8080/users
Content-Type: application/json
Accept: application/json

{
  "idUser": 4,
  "login": "loginUpdate",
  "password": "passwordUpdate",
  "userRoles": ["ADMIN"]
}

### Delete user
DELETE http://localhost:8080/users/3
Content-Type: application/json
Accept: application/json

### Delete chosen user
DELETE http://localhost:8080/users
Content-Type: application/json
Accept: application/json

{
  "login": "loginTestB"
 }

