### Find all users
GET http://localhost:8080/users
Accept: application/json
Content-Type: application/json

### Get User
GET http://localhost:8080/users/1
Content-Type: application/json
Accept: application/json

### Add User
POST http://localhost:8080/users
Content-Type: application/json
Accept: application/json

{
  "login": "loginTest",
  "password": "passwordTest",
  "userRoles": ["ADMIN"]
}

### Update User
PUT http://localhost:8080/users/1
Content-Type: application/json
Accept: application/json

{
  "login": "loginUpdate",
  "password": "passwordUpdate",
  "userRoles": ["USER"]
}

### Delete User
DELETE http://localhost:8080/users/1
Content-Type: application/json
Accept: application/json

###
POST http://localhost:8080/users/2/roles
Content-Type: application/json
Accept: application/json

{
  "role": "USER"
}